# Generated by Django 5.0 on 2023-12-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='user',
            new_name='host',
        ),
    ]
