# Generated by Django 5.0 on 2024-01-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='job',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
