# Generated by Django 5.0 on 2024-01-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_projectmember_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='job',
            field=models.CharField(max_length=20),
        ),
    ]
