# Generated by Django 5.0 on 2024-01-09 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_projectmember_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='mission',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='vision',
            field=models.CharField(max_length=150),
        ),
    ]
